version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running unit tests..."
      # This command will discover and run tests in files named test_*.py
      # If any test fails, CodeBuild stops here with a FAILED status.
      - python -m pytest --junitxml=test-reports/report.xml

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "packaging the application ..."
      - zip -r application.zip .
artifacts:
  files:
    # This specifies which file(s) to save as the output of this build stage
    - application.zip